"use client";

import { useState, useEffect, useRef } from "react";
import {
  Edit,
  Trash2,
  Phone,
  Mail,
  MapPin,
  Calendar,
  FileText,
  Sparkles,
  ClipboardList,
  RefreshCw,
  Check,
  X,
  Download,
  Plus,
} from "lucide-react";
import { Button } from "@/components/ui";
import {
  usePatient,
  useObservations,
  useDeletePatient,
  useGenerateSummary,
  useAnalyzeMail,
  useUpdatePatient,
  useUpdateObservation,
} from "@/hooks";
import { calculateAge, formatDate } from "@/lib/date-utils";
import { useTabsStore } from "@/stores/tabs-store";
import { useQuickCreateStore } from "@/stores/quick-create-store";
import { useAppModule } from "@/components/layout/use-app-module";
import { PatientForm } from "./patient-form";
import { TypeObservation, ModuleType } from "@/types";

interface PatientCardProps {
  patientId: string;
}

export function PatientCard({ patientId }: PatientCardProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [mailContent, setMailContent] = useState("");
  const [mailAnalysis, setMailAnalysis] = useState<string | null>(null);
  const [isEditingNotes, setIsEditingNotes] = useState(false);
  const [editedNotes, setEditedNotes] = useState("");
  const [expandedObsId, setExpandedObsId] = useState<string | null>(null);
  const [editingObsContent, setEditingObsContent] = useState("");
  const hasAutoGenerated = useRef(false);
  const observationsContainerRef = useRef<HTMLDivElement>(null);

  const { data: patient, isLoading } = usePatient(patientId);
  const { data: observations } = useObservations({ patientId });
  const deletePatient = useDeletePatient();
  const generateSummary = useGenerateSummary();
  const analyzeMail = useAnalyzeMail();
  const updatePatient = useUpdatePatient();
  const updateObservation = useUpdateObservation();
  const { removeTab, updateTab } = useTabsStore();
  const { trigger } = useQuickCreateStore();
  const { setActiveModule } = useAppModule();

  // Auto-generate summary on first load if no summary exists and there are observations
  useEffect(() => {
    if (
      patient &&
      !patient.resume_ia &&
      observations &&
      observations.length > 0 &&
      !hasAutoGenerated.current &&
      !generateSummary.isPending
    ) {
      hasAutoGenerated.current = true;
      generateSummary.mutate(patientId);
    }
  }, [patient, observations, patientId, generateSummary]);

  // Handle click outside to save observation
  useEffect(() => {
    const handleClickOutside = async (event: MouseEvent) => {
      if (
        expandedObsId &&
        editingObsContent !== "" &&
        observationsContainerRef.current &&
        !observationsContainerRef.current.contains(event.target as Node)
      ) {
        // Find the observation being edited
        const obs = observations?.find((o) => o.id === expandedObsId);
        if (obs && editingObsContent !== obs.contenu) {
          await updateObservation.mutateAsync({
            id: expandedObsId,
            contenu: editingObsContent,
          });
        }
        setExpandedObsId(null);
        setEditingObsContent("");
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [expandedObsId, editingObsContent, observations, updateObservation]);

  const handleStartEditNotes = () => {
    setEditedNotes(patient?.notes || "");
    setIsEditingNotes(true);
  };

  const handleSaveNotes = async () => {
    try {
      await updatePatient.mutateAsync({
        id: patientId,
        notes: editedNotes,
      });
      setIsEditingNotes(false);
    } catch (error) {
      alert("Erreur lors de la sauvegarde des notes");
    }
  };

  const handleCancelEditNotes = () => {
    setIsEditingNotes(false);
    setEditedNotes("");
  };

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent" />
      </div>
    );
  }

  if (!patient) {
    return (
      <div className="flex h-full items-center justify-center text-gray-500">
        Patient non trouve
      </div>
    );
  }

  if (isEditing) {
    return (
      <PatientForm
        patient={patient}
        onSuccess={(updatedPatient) => {
          setIsEditing(false);
          updateTab(`patient-${patientId}`, {
            title: `${updatedPatient.nom} ${updatedPatient.prenom}`,
          });
        }}
        onCancel={() => setIsEditing(false)}
      />
    );
  }

  const handleDelete = async () => {
    if (
      confirm(
        `Voulez-vous vraiment supprimer le dossier de ${patient.nom} ${patient.prenom} ?`
      )
    ) {
      await deletePatient.mutateAsync(patientId);
      removeTab(`patient-${patientId}`);
    }
  };

  const handleGenerateSummary = async () => {
    try {
      await generateSummary.mutateAsync(patientId);
    } catch (error) {
      alert("Erreur lors de la generation du resume");
    }
  };

  const handleAnalyzeMail = async () => {
    if (!mailContent.trim()) return;

    try {
      const result = await analyzeMail.mutateAsync({
        patientId,
        mailContent,
      });
      setMailAnalysis(result.analysis);
      setMailContent("");
    } catch (error) {
      alert("Erreur lors de l'analyse du mail");
    }
  };

  const getObservationTypeLabel = (type: TypeObservation) => {
    const labels: Record<TypeObservation, string> = {
      [TypeObservation.CONSULTATION]: "Consultation",
      [TypeObservation.SUIVI]: "Suivi",
      [TypeObservation.URGENCE]: "Urgence",
      [TypeObservation.TELEPHONE]: "Telephone",
      [TypeObservation.RESULTATS]: "Resultats",
      [TypeObservation.COURRIER]: "Courrier",
      [TypeObservation.REUNION]: "Reunion",
      [TypeObservation.NOTE]: "Note",
    };
    return labels[type] || type;
  };

  const handleNewObservation = () => {
    // Switch to Observations module and trigger the form with this patient
    setActiveModule(ModuleType.OBSERVATIONS);
    setTimeout(() => {
      trigger(ModuleType.OBSERVATIONS, { patientId });
    }, 50);
  };

  const handleExportPatient = async () => {
    if (!patient) return;

    try {
      // Build the text report
      let text = `DOSSIER PATIENT\n`;
      text += `${"=".repeat(60)}\n\n`;
      text += `${patient.nom.toUpperCase()} ${patient.prenom}\n`;

      if (patient.sexe) {
        text += `Sexe: ${patient.sexe}\n`;
      }
      if (patient.date_naissance) {
        text += `Date de naissance: ${formatDate(patient.date_naissance)}\n`;
        text += `Âge: ${calculateAge(patient.date_naissance)}\n`;
      }
      if (patient.telephone) {
        text += `Téléphone: ${patient.telephone}\n`;
      }
      if (patient.email) {
        text += `Email: ${patient.email}\n`;
      }
      if (patient.adresse) {
        text += `Adresse: ${patient.adresse}\n`;
      }
      if (patient.secteur) {
        text += `Secteur: ${patient.secteur}\n`;
      }

      if (patient.notes) {
        text += `\nNOTES:\n${patient.notes}\n`;
      }

      if (patient.resume_ia) {
        text += `\nRÉSUMÉ:\n${patient.resume_ia}\n`;
      }

      text += `\n${"=".repeat(60)}\n`;
      text += `OBSERVATIONS (${observations?.length || 0})\n`;
      text += `${"=".repeat(60)}\n\n`;

      if (!observations || observations.length === 0) {
        text += "Aucune observation enregistrée.\n";
      } else {
        // Sort observations by date (most recent first)
        const sortedObs = [...observations].sort((a, b) =>
          new Date(b.date).getTime() - new Date(a.date).getTime()
        );

        sortedObs.forEach((obs, index) => {
          text += `${index + 1}. ${formatDate(obs.date)} - ${getObservationTypeLabel(obs.type_observation)}\n`;

          if (obs.age_patient_jours !== undefined) {
            const years = Math.floor(obs.age_patient_jours / 365);
            const months = Math.floor((obs.age_patient_jours % 365) / 30);
            const days = obs.age_patient_jours % 30;

            if (years > 0) {
              text += `   Âge: ${years} an${years > 1 ? 's' : ''}`;
              if (months > 0) text += ` ${months} mois`;
              text += `\n`;
            } else if (months > 0) {
              text += `   Âge: ${months} mois`;
              if (days > 0) text += ` ${days} jours`;
              text += `\n`;
            } else {
              text += `   Âge: ${days} jour${days > 1 ? 's' : ''}\n`;
            }
          }

          if (obs.contenu) {
            text += `\n   ${obs.contenu.split('\n').join('\n   ')}\n`;
          }
          text += `\n${"-".repeat(40)}\n\n`;
        });
      }

      // Copy to clipboard
      await navigator.clipboard.writeText(text);
      alert("Dossier patient copié dans le presse-papier !");
    } catch (error) {
      console.error("Erreur lors de l'export:", error);
      alert("Erreur lors de la copie dans le presse-papier");
    }
  };

  return (
    <div className="h-full overflow-auto">
      {/* Header with coordinates */}
      <div className="border-b border-gray-200 bg-white p-4">
        <div className="flex items-start justify-between gap-4">
          {/* Name, DOB, Age */}
          <div className="flex-1">
            <h2 className="text-xl font-bold text-gray-900">
              {patient.nom.toUpperCase()} {patient.prenom}
            </h2>
            {patient.date_naissance && (
              <p className="text-sm text-gray-600">
                Ne(e) le {formatDate(patient.date_naissance)} • {calculateAge(patient.date_naissance)}
              </p>
            )}
          </div>

          {/* Coordinates (reduced) */}
          <div className="flex flex-wrap items-center gap-3 text-xs text-gray-500">
            {patient.telephone && (
              <span className="flex items-center gap-1">
                <Phone className="h-3 w-3" />
                {patient.telephone}
              </span>
            )}
            {patient.email && (
              <span className="flex items-center gap-1">
                <Mail className="h-3 w-3" />
                {patient.email}
              </span>
            )}
            {patient.adresse && (
              <span className="flex items-center gap-1">
                <MapPin className="h-3 w-3" />
                {patient.adresse}
              </span>
            )}
            {patient.secteur && (
              <span className="rounded bg-gray-100 px-2 py-0.5">
                {patient.secteur}
              </span>
            )}
          </div>

          {/* Actions */}
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={() => setIsEditing(true)}>
              <Edit className="mr-1 h-3 w-3" />
              Modifier
            </Button>
            <Button variant="secondary" size="sm" onClick={handleExportPatient}>
              <Download className="mr-1 h-3 w-3" />
              Exporter
            </Button>
            <Button
              variant="danger"
              size="sm"
              onClick={handleDelete}
              isLoading={deletePatient.isPending}
            >
              <Trash2 className="mr-1 h-3 w-3" />
              Supprimer
            </Button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 p-4">
        {/* Left column - AI Summary + Mail import + Notes */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-gray-900">Resume IA</h3>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleGenerateSummary}
              isLoading={generateSummary.isPending}
            >
              <RefreshCw className="mr-2 h-4 w-4" />
              Actualiser
            </Button>
          </div>

          {patient.resume_ia ? (
            <div className="rounded-md bg-blue-50 p-4 text-sm text-gray-700 whitespace-pre-wrap">
              {patient.resume_ia}
            </div>
          ) : generateSummary.isPending ? (
            <div className="rounded-md border-2 border-dashed border-gray-200 p-4 text-center text-sm text-gray-500">
              <div className="flex items-center justify-center gap-2">
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-blue-600 border-t-transparent" />
                Generation du resume en cours...
              </div>
            </div>
          ) : (
            <div className="rounded-md border-2 border-dashed border-gray-200 p-4 text-center text-sm text-gray-500">
              Aucun resume genere.
              <br />
              {observations && observations.length > 0
                ? "Le resume sera genere automatiquement."
                : "Ajoutez des observations pour generer un resume."}
            </div>
          )}

          {/* Mail import section */}
          <div className="mt-6">
            <h3 className="mb-2 font-semibold text-gray-900">Importer un mail</h3>
            <textarea
              value={mailContent}
              onChange={(e) => setMailContent(e.target.value)}
              placeholder="Collez le contenu d'un mail ici pour l'analyser..."
              rows={4}
              className="block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            />
            <Button
              variant="secondary"
              size="sm"
              className="mt-2"
              onClick={handleAnalyzeMail}
              isLoading={analyzeMail.isPending}
              disabled={!mailContent.trim()}
            >
              <FileText className="mr-2 h-4 w-4" />
              Analyser et integrer
            </Button>

            {mailAnalysis && (
              <div className="mt-3 rounded-md bg-green-50 p-3 text-sm text-gray-700 whitespace-pre-wrap">
                <p className="font-medium text-green-800 mb-2">Analyse du mail:</p>
                {mailAnalysis}
              </div>
            )}
          </div>

          {/* Notes section */}
          <div>
            <h3 className="mb-2 font-semibold text-gray-900">Notes</h3>
            {isEditingNotes ? (
              <div className="space-y-2">
                <textarea
                  value={editedNotes}
                  onChange={(e) => setEditedNotes(e.target.value)}
                  rows={4}
                  className="block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                  autoFocus
                />
                <div className="flex gap-2">
                  <button
                    onClick={handleSaveNotes}
                    className="flex items-center gap-1 rounded px-2 py-1 text-xs text-green-600 hover:bg-green-50"
                    disabled={updatePatient.isPending}
                  >
                    <Check className="h-3 w-3" />
                    Sauvegarder
                  </button>
                  <button
                    onClick={handleCancelEditNotes}
                    className="flex items-center gap-1 rounded px-2 py-1 text-xs text-gray-500 hover:bg-gray-100"
                  >
                    <X className="h-3 w-3" />
                    Annuler
                  </button>
                </div>
              </div>
            ) : (
              <div
                onClick={handleStartEditNotes}
                className="cursor-pointer whitespace-pre-wrap rounded-md bg-gray-50 p-3 text-sm text-gray-600 hover:bg-gray-100 transition-colors min-h-[60px]"
                title="Cliquez pour modifier"
              >
                {patient.notes || <span className="text-gray-400 italic">Cliquez pour ajouter des notes...</span>}
              </div>
            )}
          </div>
        </div>

        {/* Right column - Observations history */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-gray-900">
              Historique des observations
            </h3>
            <div className="flex items-center gap-2">
              <Button
                variant="secondary"
                size="sm"
                onClick={handleNewObservation}
              >
                <Plus className="mr-1 h-3 w-3" />
                Nouvelle observation
              </Button>
              <span className="text-sm text-gray-500">
                {observations?.length || 0} observation
                {(observations?.length || 0) !== 1 ? "s" : ""}
              </span>
            </div>
          </div>

          {observations && observations.length > 0 ? (
            <div ref={observationsContainerRef} className="max-h-[500px] space-y-2 overflow-auto">
              {observations.map((obs) => {
                const isExpanded = expandedObsId === obs.id;
                const isEditing = isExpanded && editingObsContent !== "";

                return (
                  <div
                    key={obs.id}
                    onClick={() => {
                      if (!isExpanded) {
                        setExpandedObsId(obs.id);
                        setEditingObsContent("");
                      }
                    }}
                    className={`rounded-md border p-3 text-sm cursor-pointer transition-all ${
                      isExpanded
                        ? "border-blue-300 bg-blue-50"
                        : "border-gray-200 hover:border-gray-300 hover:bg-gray-50"
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-medium text-gray-900">
                        {formatDate(obs.date)}
                      </span>
                      <span className="rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
                        {getObservationTypeLabel(obs.type_observation)}
                      </span>
                    </div>

                    {isExpanded && isEditing ? (
                      <div className="mt-2" onClick={(e) => e.stopPropagation()}>
                        <textarea
                          value={editingObsContent}
                          onChange={(e) => setEditingObsContent(e.target.value)}
                          rows={4}
                          className="w-full rounded border border-gray-300 px-2 py-1 text-sm"
                          autoFocus
                        />
                        <div className="mt-2 flex justify-end gap-2">
                          <button
                            onClick={() => {
                              setExpandedObsId(null);
                              setEditingObsContent("");
                            }}
                            className="text-xs text-gray-500 hover:text-gray-700"
                          >
                            Annuler
                          </button>
                          <button
                            onClick={async () => {
                              await updateObservation.mutateAsync({
                                id: obs.id,
                                contenu: editingObsContent,
                              });
                              setExpandedObsId(null);
                              setEditingObsContent("");
                            }}
                            className="text-xs text-blue-600 hover:text-blue-800"
                          >
                            Enregistrer
                          </button>
                        </div>
                      </div>
                    ) : isExpanded ? (
                      <div
                        onClick={(e) => {
                          e.stopPropagation();
                          setEditingObsContent(obs.contenu || "");
                        }}
                        className="mt-2 text-gray-600 cursor-text hover:bg-blue-100 rounded p-1 -m-1"
                        title="Cliquez pour modifier"
                      >
                        {obs.contenu || <span className="text-gray-400 italic">Cliquez pour ajouter du contenu...</span>}
                      </div>
                    ) : (
                      <p className="mt-1 line-clamp-2 text-gray-600">
                        {obs.contenu || <span className="text-gray-400 italic">-</span>}
                      </p>
                    )}

                    {isExpanded && !isEditing && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setExpandedObsId(null);
                        }}
                        className="mt-2 text-xs text-gray-500 hover:text-gray-700"
                      >
                        Reduire
                      </button>
                    )}
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="rounded-md border-2 border-dashed border-gray-200 p-4 text-center text-sm text-gray-500">
              <ClipboardList className="mx-auto mb-2 h-8 w-8 text-gray-300" />
              Aucune observation enregistree
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
